lib, mount/unmount

diff --git a/bk-run b/bk-run
--- a/bk-run
+++ b/bk-run
@@ -1,8 +1,20 @@
 #!/bin/bash
 
+
 bin=`dirname $0`
+. "$HOME/.bk-conf"
+. "$bin/bk-lib.sh"
+
+log "backup drive: $backup_drive"
+log "log file    : $backup_log"
 
 
-echo "TODO: mount USB drive"
-echo "TODO: update backup"
-echo "unmount USB drive"
+log "TODO: mount USB drive"
+$bin/bk-mount "$backup_drive"
+if [ $? -ne 0 ]; then
+    echo "Failed to mount $backup_drive."
+    exit 10
+fi
+
+log "TODO: update backup"
+log "unmount USB drive"
